"""
Given two strings s and t which consist of only lowercase letters.

String t is generated by random shuffling string s and then add one more letter at a random position.

Find the letter that was added in t.

Example:

Input:
s = "abcd"
t = "abcde"

Output:
e

Explanation:
'e' is the letter that was added.

"""


def find_the_difference(s, t):
    """
    :type s: str
    :type t: str
    :rtype: str
    """
    records = {}
    for c in s:
        records[c] = records.get(c, 0) + 1
    for c in t:
        if records.get(c) is None:
            return c
        records[c] -= 1
    for key in records:
        if records[key] == -1:
            return key, t


def find_the_difference_xor(s, t):
    res = 0
    for c in s:
        res ^= ord(c)
    for c in t:
        res ^= ord(c)
    return chr(res)


examples = [
    {
        "input": {
            "s": "abcd",
            "t": "bcdae"
        },
        "output": "e"
    }, {
        "input": {
            "s": "c",
            "t": "cc"
        },
        "output": "c"
    }
]


for example in examples:
    print find_the_difference(**example["input"])